"""Створення таблиці service_requests

Revision ID: 4ab93a22b8d2
Revises: 66fae9929a7e
Create Date: 2025-02-24 20:39:54.898671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ab93a22b8d2'
down_revision: Union[str, None] = '66fae9929a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_requests', sa.Column('question', sa.String(), nullable=True))
    op.alter_column('service_requests', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_requests', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('service_requests', 'question')
    # ### end Alembic commands ###
